import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import partners from '../config/partners'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jemmastables</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="aspect-w-16 aspect-h-16 md:aspect-h-8 relative overflow-hidden md:h-screen">
        <video
          autoPlay
          loop
          muted
          className="z-10 md:absolute w-auto min-w-full min-h-full max-w-none"
        >
          <source
            src="/videos/maja.mp4"
            type="video/mp4"
          />
          Your browser does not support the video tag.
        </video>
        <div className="flex items-end md:pb-14">
          <div className="flex w-full h-20 items-center justify-evenly z-20">
            {partners.map((partner, i: number) => (
              <div key={i} className="w-2/12 md:w-1/12 z-20 filter grayscale invert brightness-0 opacity-30">
                <Image src={partner.image} alt={partner.alt} width={partner.width} height={partner.height} layout="responsive" />
              </div>
            ))}
          </div>
        </div>
      </header>
    </div>
  )
}


export default Home
